### ISSUE TITLE
Birthday BBQ

### ISSUE THREAD

**Issue by jcallaghan** [jcallaghan/The-Cookbook#534]
- 12 ½ people
- 14:30 start

## Shopping

- [ ] 12 sweetcorn cobs (with leaves if possible)
- [ ] 3 x basil
- [ ] 3 x thin asparagus
- [ ] Strawberries
- [ ] Kiwi
- [ ] Grapes
- [ ] Pineapple
- [ ] Lemons
- [ ] Onions
- [ ] Watermelon
- [ ] Apricot 
- [ ] Bell peppers
- [ ] Red onions
- [ ] Courgette
- [ ] Rocket
- [ ] Carrots
- [ ] 10 x beef tomato
- [ ] Pizza pepperoni 
- [ ] 2 x streaky bacon
- [ ] 3 x prosciutto 
- [ ] Sausages (or from butchers)
- [ ] Sesame seeds
- [ ] Dough for 12 (Aldi)
- [ ] Cream cheese
- [ ] 2 x large halloumi blocks
- [ ] 3 x mozzarella balls
- [ ] Shredded mozzarella
- [ ] Solid mozzarella block
- [ ] 2 x plastic cheese
- [ ] Special cheese layer (chilli squares)
- [ ] 2 x clotted cream
- [ ] Stalk butter
- [ ] Grease paper
- [ ] Check sauce situation (mayo, ketchup, mustard)
- [ ] 2 x hot dog jars
- [ ] 18 seeded buns
- [ ] 18 hot dog buns
- [ ] Scones
- [ ] Eggs
- [ ] Self-raising flour
- [ ] Plain chocolate
- [ ] Caster sugar
- [ ] Walnuts + pecans 
- [ ] Juices
- [ ] 2 x bags ice

### Butchers

- [ ] 18 burgers
- [ ] 12 minted koftas
- [ ] 12 non-minted koftas
- [ ] 18 sausages

### Turkish shop

- [ ] 2/3 flatbread

### Night before

- [ ] Wrap #511 Prosciutto and bacon + apricot wedges
- [ ] Cake #76 + #351 
- [ ] Marinade #13 
- [ ] Wrap meat in grease proof paper

### Pre-grill

- [ ] Remove bread from packets add to bread basket + fly cover
- [ ] Condiments into basket
- [ ] Prep #37 + olive oil, pepper and balsamic glaze ahead of serving
- [ ] Add #13 onto kebab skewers
- [ ] Serve #37 on platter with rocket 

### Grill

- [ ] ~ Onion grill clean
- [ ] #13 - serve in large bowl
- [ ] #515 - serve with butter and white pepper + forks
- [ ] #37 + olive oil, pepper and balsamic glaze
- [ ] ~ Reheat + potato non-stick
- [ ] #231 + #126 
- [ ] ~ Reheat + potato non-stick
- [ ] #511 prosciutto twists + bacon and apricots twists - serve with balsamic glaze, top up rocket platter
- [ ] ~ Reheat + potato non-stick
- [ ] Koftas
- [ ] Sausages and #529
- [ ] ~ Reheat + potato non-stick
- [ ] Burgers, melted cheese, toasted buns

### Dessert

- [ ] #514 
- [ ] #351 muffins
- [ ] #76 
- [ ] Fruit platter - cocktail sticks

### Late feast

- [ ] #234 
- [ ] #235 + #251 
- [ ] #179

**Comment by jcallaghan** [comment]
## Shopping

- [x] 14 sweetcorn cobs (with leaves if possible)
- [x] 4 x basil
- [x] 4 x thin asparagus
- [x] Strawberries
- [x] Kiwi
- [x] Grapes
- [x] Pineapple
- [x] Lemons
- [ ] Onions
- [x] Watermelon
- [ ] 4 x Apricots
- [x] Blackberries
- [x] Raspberries
- [ ] Figs
- [x] 3 x bell peppers
- [x] 3 x courgette
- [x] Rocket salad
- [x] Carrots
- [x] 10 x beef tomato
- [x] 1 x cherry tomatoes 
- [x] 3 x pizza pepperoni 
- [x] 2 x streaky bacon
- [x] 4 x prosciutto 
- [x] Sausages (or from butchers)
- [x] Sesame seeds
- [ ] Dough for 12 (Aldi)
- [x] 300g cream cheese
- [x] 3 x large halloumi blocks
- [x] 3 x mozzarella balls
- [x] Shredded mozzarella
- [x] Solid mozzarella block
- [x] 2 x plastic cheese
- [ ] Special cheese layer (chilli squares)
- [ ] Yoghurt
- [x] 2 x clotted cream
- [ ] Whipped cream can
- [x] Stalk butter
- [ ] Grease paper
- [ ] Check sauce situation (mayo, ketchup, mustard)
- [x] 2 x hot dog jars
- [ ] 20 x seeded buns
- [x] 18 x hot dog buns
- [x] Scones
- [ ] 12 x eggs
- [ ] Plan + self-raising flour
- [ ] Plain chocolate
- [ ] Caster sugar
- [x] Muscovado 
- [ ] Walnuts + pecans 
- [ ] Non-alcoholic juices
- [ ] 4 x bags ice

ALDI - wines and drinks £20
Sainsbury's £141

### Butchers

- [ ] 24 burgers
- [ ] 18 minted koftas
- 2 pork pies
- Rack of lamb, French trimmed

Butchers £68

**Comment by jcallaghan** [comment]
## Cook

### Night before

- [ ] Wrap #511 Prosciutto and bacon + apricot wedges
- [ ] Cake #76 + #351 
- [ ] Marinade #13 
- [ ] Cut fruit for #535 
- [ ] Wrap meat in grease proof paper

### Pre-grill

- [ ] Remove bread from packets add to breadbasket + fly cover
- [ ] Condiments into basket
- [ ] Prep #37
- [ ] Add #13 onto kebab skewers
- [ ] Serve #37 on platter with rocket, olive oil, pepper, and balsamic glaze + sea salt

### Grill

- [ ] #537
- [ ] #13 - serve in large bowl
- [ ] #515 - serve with butter and white pepper + forks
- [ ] #37 + olive oil, pepper, and balsamic glaze
- [ ] #231 + #126 serve with sweet chilli sauce
- [ ] #511 prosciutto twists + bacon and apricots twists - serve with balsamic glaze, top up rocket platter
- [ ] Koftas - serve on the rocket platter
- [ ] Sausages (pork and beef) - server on a platter
- [ ] Spiral #529 (to order) - use cocktail sticks to create the spiral - server on a platter
- [ ] Burgers, melted cheese, toasted buns - to order

### Dessert

- [ ] #514 
- [ ] #536 
- [ ] #76 
- [ ] #535

### Late feast

- [ ] #234 
- [ ] #235 
- [ ] #251 
- [ ] #179
